language: node_js

node_js:
  - 6

script:
  - yarn install
  - yarn run build

cache:
  yarn: true
  directories:
  - node_modules

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: $BUCKET_NAME
  region: $AWS_REGION
  skip_cleanup: true
  acl: public_read
  local_dir: ./build
